# Generated by Django 2.0.8 on 2018-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '登記', 'verbose_name_plural': '登記'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.AddField(
            model_name='item',
            name='school',
            field=models.IntegerField(choices=[(1, '保良局梁周順琴小學'), (2, '湖景青松小學')], default=1, verbose_name='學校'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日期'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
    ]
